### ISSUE TITLE
Regression: NCA decryption failing on latest commit

### ISSUE THREAD

**Issue by NWPlayer123** [SciresM/hactool#27] opened 2018-06-06 09:00 UTC
Trying to extract an NCA from Nintendo's servers, https://github.com/SciresM/hactool/commit/af428a1bdea5069fef6a88a037732a161abbe282 broke (some) decryption, one NCA works, another doesn't, both verified with the SHA-256. 1.1.0 works (both pre-built and compiled), straight from repo does not. Bisected(?) it, everything up to that commit works fine. Not sure why one works and another doesn't.

**Comment by CTCaer** [comment] 2018-06-06 09:42
Maybe this one broke it for you:
https://github.com/SciresM/hactool/commit/af428a1bdea5069fef6a88a037732a161abbe282#diff-13deadd61e11ad5d2e581cd6cf902c13R55

What OS and bit flavor (32bit or 64bit) you have?

**Comment by NWPlayer123** [comment] 2018-06-06 22:00
Windows 10, latest big update, 64-bit, built on MSYS2, no changes to the config

**Comment by TheExpertNoob** [comment] 2018-06-09 13:35
I'm having just the opposite. NCAs from Raw cart dumps(and from nax0) won't extract but NCAs from CDN will extract fine (provided titlekey) As NWPlayer123 mentioned, works fine on the latest 1.1.0 release and previous version of hactool I've built.
Also Win10 prerelease.180420-1850 (64 bit) built MinGW32-make (noticed it on the commit that introduced xci logo extraction)

(just to add) Before this commit, I just used the logo that existed in the control NCA

(also to add) Restoring the diff CTCaer mentioned fixed my issue. Don't know if it broke anything else.

**Comment by hexkyz** [comment] 2018-06-10 18:22
Can you please confirm what change introduced the regression? Was it the changes on partition mounting or the cleanup on fseeko64?

**Comment by TheExpertNoob** [comment] 2018-06-10 19:39
for me, cleanup of fseeko64. reverted the diff in utils.h and It now works for me.

**Comment by NWPlayer123** [comment] 2018-06-12 02:39
was this commit, can't narrow it down any further @hexkyz 
https://github.com/SciresM/hactool/commit/af428a1bdea5069fef6a88a037732a161abbe282
might be the utils.h change @TheExpertNoob mentioned, haven't tested yet

**Comment by hexkyz** [comment] 2018-06-17 15:44
This appears to be an issue with fseek and the MSYS environment. Just to further confirm, could someone try this again under WSL? MinGW and Cygwin will probably need their own case when mapping out the fseek function.

**Comment by NWPlayer123** [comment] 2018-07-27 06:37
need to do some more testing but it seems like https://github.com/SciresM/hactool/commit/37e368b87bf2deccc4d21783e28557b240a20602#diff-13deadd61e11ad5d2e581cd6cf902c13 fixed MSYS2 compilation @SciresM

**Comment by hexkyz** [comment] 2019-10-18 18:10
Closing down this issue since it has been long fixed.

**Closed as completed by hexkyz** 2019-10-18 18:10 UTC
