### ISSUE TITLE
-k or --keyset does not prevent /.switch/prod.keys from loading

### ISSUE THREAD

**Issue by urherenow** [SciresM/hactool#113] opened 2022-08-23 14:03 UTC
I'm pretty sure the intent is to look for prod.keys or dev.keys in %home%/.switch if you DON'T specify with -k or --keyset. I was having a hard time with a certain project that only wants certain keys, the author does specify the file, but the prod.keys in my profile's .switch folder was messing up the process.

**Comment by pixeltester** [comment] 2022-08-23 14:34
README.md:

"In addition, if -k/--keyset is not set, hactool will check for the presence of a keyset file in $HOME/.switch/prod.keys (or $HOME/.switch/dev.keys if -d/--dev is set). If present, this file will automatically be loaded."

**Comment by SciresM** [comment] 2022-08-23 15:26
Not sure I understand. Where is the bug?

per main.c, the key file passed with -k is used whenever it exists. https://github.com/SciresM/hactool/blob/master/main.c#L449

local testing does prefer the file passed with -k when present to the one in prod.keys...can you clarify what the unexpected behavior is?

utils.c isn't responsible for -k key file selection...

**Comment by SciresM** [comment] 2022-08-23 15:35
Yeah, I can't reproduce at all. When I test, you can see that the stuff in ~/.switch/prod.keys gets overridden when I use -k:

![image](https://user-images.githubusercontent.com/8676005/186200511-90195ec0-c34f-425c-8b59-dd12ab4b9249.png)

I will close this issue in 24 hours without clarification.

**Comment by urherenow** [comment] 2022-08-23 15:37
utils.c 262-279. It doesn't check for the flag. Pardon me if the check is somewhere else, but see thread https://gbatemp.net/threads/info-on-sha-256-hashes-on-fs-patches.581550/post-9918507

the file is specified and present, and in the specified place and in the expected format, with ONLY the correct (expected) keys. I know there is a bug in the program I'm dealing with (it's an executable made from python scripts) since extra/unneeded keys should not halt the process, but with my prod.keys FULLY populated via Lockpick_RCM, and in the %HOME/.switch folder, this program does not work. If I rename to _prod.keys, it works perfectly, so I know the key file is both specified and correct (and in the correct location). Hactool is therefore loading prod.keys at some point, when it shouldn't.

**Comment by SciresM** [comment] 2022-08-23 15:45
The check is in main.c as mentioned/linked. The code in utils.c is not responsible for this check, the code in utils.c is supposed to find the most appropriate default-file-not-using-the-k-command-line-option. 

hactool *should* attempt to open the file in ~/.switch unconditionally, so that it can warn if it's not present -- issuing a warning when the file doesn't exist is intended.

But seriously, I can't reproduce -- see my screenshot. The code that does the selection in main.c prefers the passed keyfile.

Closing this, try to link to the actual problematic code in main.c if you think this is real.

**Closed as completed by SciresM** 2022-08-23 15:45 UTC

**Comment by urherenow** [comment] 2022-08-23 15:48
Using the command you used, without specifying any file/command after -t, I get warnings of unmatched keys, that are NOT in keys.dat. They are in /.switch/prod.keys. I'd post a screenshot, but I'd have to quickly make a bunch of nonsense keys for obvious reasons...

**Comment by SciresM** [comment] 2022-08-23 15:49
Make nonsense keys.

**Comment by SciresM** [comment] 2022-08-23 15:49
And, ideally, make a single nonsense key.

What platform are you on? Because you can see that it's behaving correctly on windows, using my build.

You can also see the code in main.c always prefers the file passed via -k.

**Comment by urherenow** [comment] 2022-08-23 15:51
![hactool](https://user-images.githubusercontent.com/6448336/186203986-71a11e94-e1fa-42c6-bc6c-0ab68f7c4a6f.png)
OR just block out the pic... these are not in keys.dat.

The author of the tool, actually removed the above mentioned lines and compiled a modded hactool for me, so my issue is solved personally. I thought I was doing my duty to report it.

**Comment by SciresM** [comment] 2022-08-23 15:52
your command line is invalid. You need to pass -t keygen, passing "-t" with nothing else will be using "-k" as the type value, and attempting to parse "keys.dat" as main input.

Also, >sigpatch, piracy is not supported.

**Comment by SciresM** [comment] 2022-08-23 15:54
(the command line in your screenshot does not have a -k argument, it has a -t argument of -k, and a main-file argument of keys.dat)

**Comment by urherenow** [comment] 2022-08-23 15:57
using -t keygen, it says Error: Rights ID 01007EF00011F0010000000000000000 already has a corresponding titlekey!

Anyway, with prod.keys renamed, it works as expected. The author built me a hactool real quick (thus me using _hactool just now) that removed those lines from utils.c, and that version works without renaming prod.keys. I'll end the convo here.

**Comment by SciresM** [comment] 2022-08-23 15:59
Sounds like you have title keys in your prod.keys (incorrect) *and* in title.keys, which is indeed an error condition. I'll lock this now.
